version: '2'
services:
  redis:
    image: redis
  server:
    image: lukasheinrich/modelinspector
    command: python app.py
    ports:
      - 5000:5000
    environment:
      MODELINSPECTOR_REDIS: redis://redis
  worker:
    image: lukasheinrich/modelinspector_worker
    environment:
      MODELINSPECTOR_REDIS: redis://redis
    command: bash -c 'source /usr/local/bin/thisroot.sh && celery worker -A tasks --concurrency 4'
